rust: condvar: avoid `pub` in example
The future move of pin-init to `syn` uncovers the following unreachable
public item in an example:

    error: unreachable `pub` item
         --> rust/doctests_kernel_generated.rs:14683:1
          |
    14683 | pub struct Example {
          | ---^^^^^^^^^^^^^^^
          | |
          | help: consider restricting its visibility: `pub(crate)`
          |
          = help: or consider exporting it for use by other crates
          = note: `-D unreachable-pub` implied by `-D warnings`
          = help: to override `-D warnings` add `#[allow(unreachable_pub)]`

There is no real downside of keeping the example as-is until the
`syn`-based pin-init is introduced, so there is no need to treat it as
a fix nor to backport it. However, we still need to change it before
introducing the new pin-init.

Thus do so.

Signed-off-by: Miguel Ojeda <ojeda@kernel.org>