kbuild: rust: warn if the out-of-tree compiler differs from the kernel one
For out-of-tree modules, in the C side, Kbuild warns if the C compiler
differs from the one used to build the kernel.

Do the same for Rust, except that we add the extra condition that Rust
support was enabled in the kernel.

For instance, the output will look like:

    warning: the Rust compiler differs from the one used to build the kernel
      The kernel was built by: rustc 1.78.0 (9b00956e5 2024-04-29)
      You are using:           rustc 1.79.0 (129f3b996 2024-06-10)

Note that the build will fail later anyway in such a case, since the
Rust compiler checks for incompatible Rust versions, e.g.:

      RUSTC [M] rust-out-of-tree-module/rust_out_of_tree.o
    error[E0514]: found crate `core` compiled by an incompatible version of rustc
      |
      = note: the following crate versions were found:
              crate `core` compiled by rustc 1.78.0 (9b00956e5 2024-04-29): rust/libcore.rmeta
      = help: please recompile that crate using this compiler (rustc 1.79.0 (129f3b996 2024-06-10)) (consider running `cargo clean` first)

Nevertheless, the added warning at the top should hopefully make the
situation clearer.

The extra condition on `CONFIG_RUST=y` is added since otherwise users
would get warnings when a Rust compiler is reachable, e.g. the most
likely case today is that they are building a C module for a kernel that
does not have Rust enabled.

However, if Rust was indeed enabled, then we do print the warning in
all cases, e.g. even if they are building a C module. While it may not
matter in some cases, it may still be a sign that something unexpectedly
changed in the environment they may want to be aware of:

    warning: the Rust compiler differs from the one used to build the kernel
      The kernel was built by: rustc 1.78.0 (9b00956e5 2024-04-29)
      You are using:           rustc 1.79.0 (129f3b996 2024-06-10)
      CC [M]  c-out-of-tree-module/c_out_of_tree.o

Note that the check will also trigger for cases where the user does not
have the Rust compiler installed, including when building a C module:

    warning: the Rust compiler differs from the one used to build the kernel
      The kernel was built by: rustc 1.78.0 (9b00956e5 2024-04-29)
      You are using:
      CC [M]  c-out-of-tree-module/c_out_of_tree.o

Suggested-by: Nicolas Schier <nicolas@fjasle.eu>
Link: https://lore.kernel.org/rust-for-linux/20240817-heavy-dancing-whale-6ae13d@lindesnes/
Signed-off-by: Miguel Ojeda <ojeda@kernel.org>